"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IFactoryWrapper__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "deployment",
                type: "address"
            },
        ],
        name: "exists",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var IFactoryWrapper__factory = /** @class */ (function () {
    function IFactoryWrapper__factory() {
    }
    IFactoryWrapper__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IFactoryWrapper__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IFactoryWrapper__factory.abi = _abi;
    return IFactoryWrapper__factory;
}());
exports.IFactoryWrapper__factory = IFactoryWrapper__factory;
